- errors/errors.go
- impl.go
- internal/util/util.go
- load/load.go
- load/load_test.go
- validate.go
- validate_test.go
Adds very basic reprocessing of errors from their raw CUE form to something more Thema-specific. This basically covers scalars, and works well enough down into nested fields. It's basically the 80% of value for 20% of effort.
This is really bare bones - i omitted putting much in the way of tests in because that's a larger TODO for Thema in general.
Part of #44.
> Basic error reprocessing

- load/load.go
It appears that at least two of the Go stdlib `fs.FS` implementations use UNIX path separators, even on windows. This creates some fun bugs. The only thing we can really do is compensate by having a normalized version of path endings in the necessary places.
> load: Normalize fs path comparisons

- encoding/jsonschema/jschema.go
- encoding/jsonschema/jschema_test.go
- encoding/openapi/oapi.go
- exemplars/exemplars.go
- exemplars/exemplars_test.go
- go.mod
- go.sum
This introduces an exporter that converts a Thema schema into JSON Schema (Wright draft 4).
What this _actually_ does is run the OpenAPI exporter (which produces OpenAPI 3.0) and then does a bunch of AST hocus pocus to turn it into JSON Schema. I based this implementation on an annoyingly large amount of reading, [this JS implementation](https://github.com/openapi-contrib/openapi-schema-to-json-schema), and [these docs](https://swagger.io/docs/specification/data-models/keywords/).
There are some odds and ends to clean up:
However, with the AST manipulation pattern in place, these are pretty trivial additions.
This could possibly eventually be contributed back to CUE directly upstream. The preferable implementation there, though, is probably to update the `encoding/openapi` exporter to …
> encoding/jsonschema: Add JSON Schema exporter

- crd/crd.cue
Convert `crd.spec.versions` to an array of objects to conform with CRD definition, and avoid errors with multiple versions.
> Update cue `crd.spec.versions` to an array

- cmd/thema/data.go
- cmd/thema/lineage_bump.go
- cmd/thema/lineage_init.go
- cmd/thema/lineage_subgen.go
- cmd/thema/load.go
- cmd/thema/main.go
- encoding/tgo/gen.go
- load/load.go
This was just a horrifying situation. This should just about do it - though in a follow-up, i'll need to make Go bindings generators aware of the new improvements and generate smarter `embed.FS` declarations.
Unfortunately, this doesn't do anything really reusable with the `load` package. Turns out, sensitivity to cwd makes the CLI case really different from the "run the binary anywhere" case. Or at least, it's seemed to so far, enough to discourage reuse.
Fixes #79
> cli: Make loaders work independent of disk state

- assignable.go
- cmd/thema/data.go
- cmd/thema/lineage_bump.go
- cmd/thema/load.go
- docs/go-usage.md
- encoding/cue/encode.go
- encoding/openapi/oapi.go
- encoding/typescript/gen.go
- exemplars/exemplars.go
- instance.go
- library.go
- lineage.go
- load/load_test.go
- schema.go
- surface.go
- vmux/mux.go
- vmux/mux_test.go
This PR refactors `UnwrapCUE()` to `Underlying()` as per https://github.com/grafana/thema/issues/70
> Change `UnwrapCUE()` to `Underlying()`

- encoding/gocode/gocode_test.go
- encoding/gocode/testdata/embed.txtar
- encoding/gocode/testdata/exemplar_defaultchange.txtar
- encoding/gocode/testdata/exemplar_disjunct.txtar
- encoding/gocode/testdata/exemplar_expand.txtar
- encoding/gocode/testdata/exemplar_narrowing.txtar
- encoding/gocode/testdata/exemplar_rename.txtar
- encoding/gocode/testdata/exemplar_single.txtar
- encoding/openapi/testdata/embed.txtar
This adds a (failed, todo) test case in encoding/gocode to check the Go code output of embedding a struct within a schema. This is something we want to improve on, and this test case provides us a target of what to fix.
Also fixes what...appear? to be some issues with output ordering in the test, i think due to the shadowed variable in subtest issue.
> gocode: Add failed embedding case, fix test

- assignable.go
- schema_test.go
`NumberKind` is just `FloatKind | IntKind`. If the scalar field in the Go type is a float, it can hold the value, and we shouldn't error.
Or at least that's my assertion :-) I don't know what peril this may cause, but it solved a BindType panic that seemed invalid.
> Do a `checkscalar` on NumberKind instead of erroring.

- encoding/gocode/gen.go
We were applying the external functions at the beginning modifying the file prior to make the fixes. This approach complicates the fixes of the Go file inside `thema` and they should be at the end.
> Apply external functions at the end to avoid undesired results

- encoding/gocode/decorators.go
- encoding/gocode/gen.go
- encoding/gocode/gocode_test.go
- encoding/gocode/testdata/comments.txtar
- encoding/gocode/testdata/exemplar_defaultchange.txtar
- encoding/gocode/testdata/exemplar_disjunct.txtar
- encoding/gocode/testdata/exemplar_expand.txtar
- encoding/gocode/testdata/exemplar_narrowing.txtar
- encoding/gocode/testdata/exemplar_rename.txtar
- encoding/gocode/testdata/exemplar_single.txtar
- encoding/gocode/testdata/multi_type.txtar
- encoding/gocode/testdata/pointers.txtar
- encoding/gocode/testdata/underscores.txtar
- internal/txtartest/txtar.go
Remove underscores in Go type names, as well as in the comment before the type and in references to these types.
Also fix a small issue running tests on Windows.
Fixes https://github.com/grafana/schematization-and-as-code-project/issues/66
> Remove underscores in Go names

- schema.go
- schema_test.go
- surface.go
- surface_test.go
Fix `func (sv SyntacticVersion) Less(osv SyntacticVersion) bool` and add some tests for it and for related schema functions. 
Also fix `LatestInMajor` function that returns an out of range error if the next major version doesn't exist.
> Fix surface Less function and add tests

- internal/deepmap/oapi-codegen/pkg/codegen/utils.go
`Oapi-codegen` was forked inside the library and it has a bug that it isn't able to detect that a duplicate field is the same. Mainly because its checking two pointers with equal operator.
This was reported and a PR was created in their repository to fix that bug.
> Fix oapi-codegen check

- schema.go
- schema_test.go
- surface.go
This pull request actually implements (previously as `panic("TODO")`) the `Examples() map[string]*Instance` method on `*schemaDef` and surfaces it, in order to get the power of defined examples from code, for instance, for testing purposes.
> Schema: implementation for Examples()

- instance_test.go
- testdata/internal/basic.cue
- testdata/lineage/basic-multiversion.txtar
- translate.cue
_(Descendant of https://github.com/grafana/thema/pull/141)_
It fixes the `Translate()` operation [when from and to versions are the same](https://github.com/grafana/thema/blob/main/translate.cue#L128), because the current implementation produces an error in such case:
```
_objold.steps: conflicting values [...#TranslatedInstance] and {} (mismatched types list and struct):
./testdata/internal/schmoo.cue:55:10
./translate.cue:37:10
./translate.cue:45:10
./translate.cue:128:16
```
> thema: Fix Translate() to same version

- encoding/gocode/gocode_test.go
- lineage_test.go
- testdata/invalidlineage/addremove.txtar
- testdata/lineage/basic-multiversion.txtar
- testdata/lineage/unifyref.txtar
This adds two known failure cases to the test corpus, and disables each case by marking them as `ToDo`:
* Adding a required field is not considered a backwards incompatible, so lineages are allowed to bind
* Go code generation does not embed or inline unified structs
> corpus: Add two known failure cases

- instance_test.go
It slightly modifies the `TestInstance_Translate` test to stop shadowing the `sch` variable used for both, the _src_ and _dst_ of the `Translate` operation, which is behaving as expected but might cause issues and/or misunderstandings in the feature.
> thema: Fix undesired variable shadow on Instance.Translate test

- instance.go
- instance_test.go
It adds a call to `Default()` after calling the CUE `#Translate` to try to return a concrete result, and deal with inconsistently-shaped instances from `Translate` and `Validate`, as described in #155.
It also adds a regression test specifically checking what's described on the issue. 
Fixes #155
> thema: Try to return a concrete result from #Translate

- encoding/typescript/gen.go
It helps to unblock: https://github.com/grafana/grafana/pull/68034
Looks like that passing `_#schema` definition makes a complex cue struct that Cuetsy is unable to iterate correctly and we didn't find a proper solution in Cuetsy for that.
So instead of passing this `_#schema`, we are passing its inner values (`schema` and `_join`) and merge them after that to make it works.
> Fix extends generation for TS files

- lineage.cue
- testdata/lineage/basic-multiversion.txtar
As reported by @mildwonkey and discussed [here](https://raintank-corp.slack.com/archives/C03BH67DS2J/p1686064633700929) and [here](https://raintank-corp.slack.com/archives/C03BH67DS2J/p1686067192429709?thread_ts=1686049601.258189&cid=C03BH67DS2J), the `Translate` operation panics with `index out of range [2] with length 2` when there's more than two majors (for instance `0.0`, `1.0` and `2.0`) in the lineage.
So, after some debugging, I realized the calc of the intermediate variable `_basis` was wrong, because as stated in the comment, it _`keeps the index of the first schema in each major version within the overall canonical schema sort ordering`_, so for example, with versions: `0.0`, `0.1`, `0.2`, `0.3`,`1.0`, `1.1` and `2.0`, I'd expect it to be `[0, 4, 6]` but it was used to be `[0, …
> Lineage: Fix intermediate variable calc

- encoding/gocode/decorators.go
- internal/deepmap/oapi-codegen/pkg/codegen/codegen_test.go
- internal/deepmap/oapi-codegen/pkg/codegen/schema.go
- internal/deepmap/oapi-codegen/pkg/codegen/template_helpers.go
- testdata/lineage/any.txtar
- testdata/lineage/go-any.txtar
Does what it says in the title.
Fixes: https://github.com/grafana/thema/issues/138
> Chore: Generate `any` instead of `interface{}` in Go code

- assignable.go
- encoding/cue/encode.go
- errors/errors.go
- impl.go
- instance.go
- lineage.go
- schema.go
- surface.go
Assorted bits of housekeeping, related to thema readiness goals.
* Adds a bunch of missing godoc
* Gets rid of some unused code
* Adds internal checks on `thema.Instance` to ensure that it panics if not created by the system itself
> thema: Tidy up base package and docs

- lineage.cue
- testdata/invalidlineage/second-schema-versionless.txtar
These 2 functions make the generation slower and in case of changes in [this PR](https://github.com/grafana/grafana/pull/62142/files#diff-abdfd6a9318ae27ef245c1da7557b327ca1e4e6a10ee220b76e162c6865eeb28R344), it hangs forever...
The dashboard generation in my local took 1min with 27sec.
Looks like that at the moment we aren't use them (?), so I commented them to unblock the dashboard changes.
> Comment Pick and PickDef to make generation faster

- assignable.go
- assignable_test.go
- encoding/gocode/gocode_test.go
- go.mod
- go.sum
- testdata/lineage/union-null.txtar
Currently, having a `| null` ends up creating undesirable behavior for certain generated Go types - in particular, we see an `int64 | null` come across as `*int` instead of `*int64`.  (Actually, it seems to be wider - a disjunction with the sized keyword types causes the loss of precision in generated Go types).
Looks like the best fix is in our fork of oapi-codegen. PR so far just introduces a test case showing the problem - no fix.
> gocode: Generate correct go types in unions will `null`

- validate.go
- validate_test.go
This is a first pass on refining error messages, with the following improvements:
- Hide CUE path details from validation error output, just display the failing attribute name (fixes #150) 
- Remove the spammy message, which looked weird for a library error
- Simplify the error message for well known numeric formats (`int64` instead of `int & >=-9223372036854775808 & <=9223372036854775807"`)
- Add a new case within `mungeValidateErr` to handle uncovered error case with msg `invalid value %v (out of bound %s)`
Thank you all!
> First pass on refining error messages

- cmd/thema/data.go
- errors/errors.go
- instance.go
- instance_test.go
- validate.go
- vmux/typed.go
- vmux/untyped.go
This PR introduces better error handling for `Translate`.
The function signature is remaining the same for `Translate`, given the aspiration to eventually have it not return errors (as described in the new docs for it). It will still panic if errors occur.
But, we also introduce `TranslateErr`, which returns errors instead of panicking. All errors which could emerge from `TranslateErr` are instances (`errors.Is`) of the new `ErrInvalidLens` sentinel error value. (That won't actually work yet because we're still figuring out how to use cockroachdb/errors in the context of #164, but once we do this should "Just Work")
The error sentinel disambiguation will be especially helpful in the context of vmuxers, where a non-nil error could _either_ come from the validate step, or from the translate …
> feat: Return sane errors from Translate

- cmd/thema/lineage_subgen.go
- encoding/gocode/binding.tmpl
- encoding/gocode/gen.go
This fixes `thema lineage gen gobindings` to properly handle `-p` arguments, and ensures the resulting generated bindings file contains a properly quoted path.
Same as #131.
> gocode: Fix subpath generation in bindings

- encoding/cue/rewrite_test.go
- encoding/gocode/gocode_test.go
- encoding/openapi/oapi_test.go
- instance_test.go
- internal/txtartest/vanilla/bench.go
- internal/txtartest/vanilla/vanilla_txtar.go
- lineage_test.go
- testdata/invalidlineage/defonly.txtar
- testdata/invalidlineage/empty.txtar
- testdata/isappendonly/invalid/boundaries.txtar
- testdata/isappendonly/invalid/default.txtar
- testdata/isappendonly/invalid/embedref.txtar
- testdata/isappendonly/invalid/nested.txtar
- testdata/isappendonly/invalid/noref.txtar
- testdata/isappendonly/invalid/optional.txtar
- testdata/isappendonly/invalid/refstruct.txtar
- testdata/isappendonly/invalid/stringconstraint.txtar
- testdata/lineage/maps.txtar
- testdata/lineage/scalars.txtar
- testdata/lineage/trivial-two-comments.txtar
- testdata/lineage/trivial-two.txtar
- validate.go
- validate_test.go
This PR adds a test case that relies on the existing corpus of lineages and schemas to test the validation process.
The idea is to extend the current corpus with examples of inputs to validate against, see the errors that come out, evaluate their correctness/friendliness, and then implement the necessary fixes.
Here we focused mainly on being able to run this type of test. A following PR will augment the corpus with more test cases, that we can rely on to safely refactor our "error munging" function.
> Test `Schema.Validate()` against the corpus

- bind.go
- errors/errors.go
- gomig_test.go
- instance.go
- lineage.go
- surface.go
- testdata/lineage/basic-multiversion.txtar
This introduces an alternate mechanism for writing lenses: passing in a slice of `ImperativeLens` to `BindLineage`:
```go
type ImperativeLens struct {
To, From SyntacticVersion
Mapper   func(inst *Instance, to Schema) (*Instance, error)
}
```
where each function has exactly the same scope of responsibility as would otherwise be fulfilled by a declarative lens written in CUE.
The caller provides these via a new `BindOption` called `ImperativeLenses()`. In the current implementation, the caller must choose to implement their lenses entirely in Go, or entirely in CUE. We could relax this later.
This isn't fully ready - definitely needs more tests, and the requisite changes to `Translate()` aren't yet implemented. (Though i think those will be like another 40 LoC...trivial). But the test that …
> thema: Initial pass at Go lenses/migrations

- bind.go
- internal/compat/compat.go
- lineage_test.go
- testdata/invalidlineage/compat/change-default.txtar
- testdata/invalidlineage/compat/remove-optional.txtar
- testdata/invalidlineage/compat/remove-required.txtar
- testdata/invalidlineage/compat/union-reduction.txtar
I'm not sure i've ever been so delighted to put up a PR as this one!
We had [three cases](https://github.com/grafana/thema/pull/193/files#diff-cfb73ed19a60f7847a9bae1ae36848406c2411d1f11f6c3610f9308d5eefe97bL69-L71) where the way we were invoking and constructing arguments to `cue.Value.Subsume()` was not behaving as expected - removing required fields, removing optional fields, and changing a default value. Clearly, these are all significant cases that we should expect folks will routinely encounter.
All three of these are now fixed. The only remaining exception cases involve additional lineage invariants that Thema is adding - nothing related to backwards compatibility.
The entire fix here was tweaking two lines:
- Checking the closed def (`_#schema`) instead of the original, typically …
> thema: Fix backwards compatibility checking bugs

- assignable.go
Fix list checking logic to include default values in list expression length check (i.e. check that there are two values when a default one is present), since the underlying issue in CUE has been resolved - calling `.Expr` no longer drops the default value.
The reason is above, the underlying issue in CUE seems to have been resolved. This fixes a weird issue when using Thema with https://github.com/grafana/grafana-app-sdk and the following schema:
```cue
package kinds
test: {
name:  "Test"
group: "some"
crd: {
scope: "Namespaced"
}
codegen: {
backend:  true
frontend: false
}
lineage: {
schemas: [{
version: [0, 0]
schema: {
#Struct: {
foo: string
}
#AnotherStruct: {
foo: #Struct
}
spec: {
foo: string
}
status: {
foo: [...#Struct]
bar: [...#AnotherStruct]
}
}
}]
}
}
```
Which results in a …
> Fix invalid unassignability check for lists of structs
